# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b16a87235cb08884ff5ec99293ad4b4d5f4c4437d5a619d4238d05a27748a4ebf026f8367474cb13b8691a9a48da6d21d350f51b7d77d678c9fc59ce5ea37a

test:
  secret_key_base: a5adeb7068ccbd852eda4492b9b7345ca9161336e930800f32b807d637cd674a458f0723e3b79943b31b174c3020fcc65f9136d98832fb09b948b5c6f2c2d00d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
